# Generated by Django 3.0.10 on 2020-10-14 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('link', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.ManyToManyField(blank=True, related_name='watchlistlisting', to='auctions.Listing')),
                ('userid', models.ManyToManyField(blank=True, related_name='watchlistuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlisting', to='auctions.Listing')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('closed', models.BooleanField(default=False)),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidlisting', to='auctions.Listing')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
