# Generated by Django 3.0.10 on 2020-10-16 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201015_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='userid',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='userid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='watchlistuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
