# Generated by Django 3.0.10 on 2020-10-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201016_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listingid',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listingid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlistlisting', to='auctions.Listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
